# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default=b'none', max_length=50)),
                ('answer_name', models.CharField(default=b'admin', max_length=50)),
                ('comment', models.CharField(default=b'none', max_length=200)),
                ('plusOne', models.BooleanField(default=False)),
                ('willCome', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('isEditable', models.BooleanField(default=True)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default=b'admin', max_length=50)),
                ('vender_name', models.CharField(default=b'a', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('descrption', models.CharField(max_length=200)),
                ('event_time', models.CharField(default=b'1/1/1970', max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('plusOne', models.BooleanField(default=False)),
                ('isFinal', models.BooleanField(default=False)),
                ('venderPermitted', models.BooleanField(default=True)),
                ('totalCounts', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('guest_name', models.CharField(max_length=50)),
                ('isAnswered', models.BooleanField(default=False)),
                ('isFinal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('vender_name', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.Event')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.Event'),
        ),
    ]
