# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='totalCounts',
            field=models.IntegerField(default=0),
        ),
    ]
