# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default=b'none', max_length=50)),
                ('answer_name', models.CharField(default=b'admin', max_length=100)),
                ('comment', models.CharField(default=b'none', max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
                ('plusOne', models.BooleanField(default=False)),
                ('willCome', models.BooleanField(default=False)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default=b'admin', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('descrption', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('place', models.CharField(max_length=50)),
                ('plusOne', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event'),
        ),
    ]
