# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170228_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='descrption',
            new_name='description',
        ),
    ]
