# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170228_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='descrption',
        ),
    ]
