# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.CharField(default=b'1/1/1970', max_length=50),
        ),
    ]
