# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_answer_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
