# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170301_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vender_name',
            field=models.CharField(default=b'a', max_length=50),
        ),
    ]
