# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_event_vender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
    ]
