# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_relationship_isfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isEditable',
            field=models.BooleanField(default=False),
        ),
    ]
