# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20170301_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venderPermitted',
            field=models.BooleanField(default=True),
        ),
    ]
